exports.seed = async function(knex) {
  
  await knex('food_items').del();

  await knex('food_items').insert([
    { id: 1, name: 'Egg', average_grams_per_unit: '50.00', measurement_type: 'quantity' },
    { id: 2, name: 'Banana', average_grams_per_unit: '120.00', measurement_type: 'quantity' },
    { id: 3, name: 'Chicken Breast', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 4, name: 'Rice (cooked)', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 5, name: 'Almonds', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 6, name: 'Apple', average_grams_per_unit: '182.00', measurement_type: 'quantity' },
    { id: 7, name: 'Bread Slice', average_grams_per_unit: '38.00', measurement_type: 'quantity' },
    { id: 8, name: 'Milk', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 9, name: 'Potato', average_grams_per_unit: '150.00', measurement_type: 'quantity' },
    { id: 10, name: 'Cheddar Cheese', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 11, name: 'Orange', average_grams_per_unit: '131.00', measurement_type: 'quantity' },
    { id: 12, name: 'Tomato', average_grams_per_unit: '123.00', measurement_type: 'quantity' },
    { id: 13, name: 'Cucumber', average_grams_per_unit: '201.00', measurement_type: 'quantity' },
    { id: 14, name: 'Avocado', average_grams_per_unit: '150.00', measurement_type: 'quantity' },
    { id: 15, name: 'Carrot', average_grams_per_unit: '61.00', measurement_type: 'quantity' },
    { id: 16, name: 'Oatmeal', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 17, name: 'Peanut Butter', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 18, name: 'Spinach', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 19, name: 'Broccoli', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 20, name: 'Tofu', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 21, name: 'Strawberry', average_grams_per_unit: '12.00', measurement_type: 'quantity' },
    { id: 22, name: 'Blueberry', average_grams_per_unit: '0.50', measurement_type: 'quantity' },
    { id: 23, name: 'Grapes', average_grams_per_unit: '5.00', measurement_type: 'quantity' },
    { id: 24, name: 'Pear', average_grams_per_unit: '178.00', measurement_type: 'quantity' },
    { id: 25, name: 'Pineapple Slice', average_grams_per_unit: '80.00', measurement_type: 'quantity' },
    { id: 26, name: 'Yogurt (plain)', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 27, name: 'Cottage Cheese', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 28, name: 'Beef Steak', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 29, name: 'Lamb Chop', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 30, name: 'Fish Fillet', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 31, name: 'Shrimp', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 32, name: 'Peas', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 33, name: 'Corn (cooked)', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 34, name: 'Mango', average_grams_per_unit: '200.00', measurement_type: 'quantity' },
    { id: 35, name: 'Watermelon Slice', average_grams_per_unit: '280.00', measurement_type: 'quantity' },
    { id: 36, name: 'Kiwi', average_grams_per_unit: '75.00', measurement_type: 'quantity' },
    { id: 37, name: 'Dates', average_grams_per_unit: '7.10', measurement_type: 'quantity' },
    { id: 38, name: 'Cashews', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 39, name: 'Walnuts', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 40, name: 'Hazelnuts', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 41, name: 'Sunflower Seeds', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 42, name: 'Sweet Potato', average_grams_per_unit: '130.00', measurement_type: 'quantity' },
    { id: 43, name: 'Zucchini', average_grams_per_unit: '196.00', measurement_type: 'quantity' },
    { id: 44, name: 'Eggplant', average_grams_per_unit: '548.00', measurement_type: 'quantity' },
    { id: 45, name: 'Lettuce Leaf', average_grams_per_unit: '15.00', measurement_type: 'quantity' },
    { id: 46, name: 'Green Beans', average_grams_per_unit: null, measurement_type: 'grams' },
    { id: 47, name: 'Mushroom', average_grams_per_unit: '18.00', measurement_type: 'quantity' },
    { id: 48, name: 'Onion', average_grams_per_unit: '110.00', measurement_type: 'quantity' },
    { id: 49, name: 'Garlic Clove', average_grams_per_unit: '3.00', measurement_type: 'quantity' },
    { id: 50, name: 'Bell Pepper', average_grams_per_unit: '120.00', measurement_type: 'quantity' },
    { id: 51, name: 'Olives', average_grams_per_unit: '4.00', measurement_type: 'quantity' }
  ]);
};
